# Generated by Django 5.0.7 on 2024-08-04 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=20, unique=True)),
                ('member_password', models.CharField(max_length=128)),
                ('member_birth', models.DateField()),
                ('member_address', models.CharField(max_length=200, null=True)),
                ('last_update', models.DateField(default=datetime.datetime(2024, 8, 4, 20, 44, 25, 807694))),
            ],
        ),
    ]
