# Generated by Django 5.0.7 on 2024-08-04 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2024, 8, 4, 20, 47, 4, 686572)),
        ),
    ]
