# Generated by Django 5.0.7 on 2024-08-09 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 15, 11, 13, 19169)),
        ),
    ]
