# Generated by Django 5.0.7 on 2024-08-04 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2024, 8, 4, 20, 50, 25, 275187)),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_address',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
