# Generated by Django 5.0.7 on 2024-08-04 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_member_last_update_alter_member_member_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_address',
        ),
        migrations.AddField(
            model_name='member',
            name='member_email',
            field=models.EmailField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2024, 8, 4, 21, 22, 6, 649947)),
        ),
    ]
