# Generated by Django 5.0.7 on 2024-08-08 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_remove_member_member_address_member_member_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 8, 14, 57, 17, 453020)),
        ),
    ]
