# Generated by Django 5.0.7 on 2024-08-08 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_alter_member_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_avatar',
            field=models.CharField(default='empty.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 8, 15, 7, 1, 907984)),
        ),
    ]
